FROM registry.docker.com/rockylinux/rockylinux:10

## Update and setup Rocky
RUN dnf update -y && \
    dnf install -y dnf-utils epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf update -y

## Install kernel dependencies and configure Dracut
RUN dnf install -y dracut && \
    echo 'hostonly="no"' > /etc/dracut.conf.d/wwinit.conf

## RPi repo and kernel
RUN dnf install -y rocky-release-rpi && \
    dnf install -y --setopt=install_weak_deps=False kernel-rpi-4k-core kernel-rpi-firmware rpi-firmware-bluez rpi-firmware-nonfree

## Install tools
RUN dnf install -y ca-certificates procps zstd jq yq && \
    dnf install -y initscripts-service cpio pigz && \
    dnf install -y openssh openssh-clients openssh-server iproute iputils NetworkManager sudo && \
    dnf install -y nano vim less bash-completion

## Setup .mount units
COPY *.mount /etc/systemd/system/
RUN echo "PARTLABEL=rootfs / ext4 defaults,noatime 0 1" > /etc/fstab && \ 
    systemctl enable boot-efi.mount

## Configure system
ENV OS_RELEASE='el10'
RUN passwd -d root && \
    sed -i '/alias/d' /root/.bashrc && \
    systemctl enable sshd.service && \
    cp /dev/null /etc/machine-id
COPY --chmod=600 *.nmconnection /etc/NetworkManager/system-connections/
COPY config.txt cmdline.txt /boot/efi/
COPY authorized_keys /root/.ssh/authorized_keys
