FROM registry.docker.com/library/debian:13
ENV OS_RELEASE='debian13'

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

## Update and setup Debian
RUN apt-get update && \
    apt-get install --yes apt-utils && \
    apt-get dist-upgrade --yes --purge

## Raspberry Pi OS Repository
RUN . /etc/os-release && \
    echo "deb http://archive.raspberrypi.org/debian/ ${VERSION_CODENAME} main" >> /etc/apt/sources.list.d/raspi.list && \
    apt-get update --allow-insecure-repositories && \
    apt-get install --yes --allow-unauthenticated raspberrypi-archive-keyring && \
    apt-get update && \
    apt-get dist-upgrade --yes

## Install base packages
RUN apt-get install --yes --no-install-recommends ca-certificates curl jq zstd cpio pigz procps iproute2 && \
    apt-get install --yes --no-install-recommends init udev dbus polkitd && \
    apt-get install --yes --no-install-recommends systemd-timesyncd systemd-resolved ifupdown && \
    apt-get install --yes --no-install-recommends openssh-server python3 && \
    apt-get install --yes nano vim less bash-completion iputils-ping bind9-host

## Install and configure Dracut first (remove password for dracut initramfs)
RUN passwd -d root && \
    apt-get install --yes dracut && \
    echo 'hostonly="no"' > /etc/dracut.conf.d/wwinit.conf

## FIXME: patch dracut to allow dracut emergency shell without password
RUN mv -v /usr/lib/dracut/modules.d/60systemd-sysusers /usr/lib/dracut/modules.d/99systemd-sysusers

## Install and configure Warewulf Dracut
ARG WW_VERSION="4.6.4"
RUN apt-get install --yes dmidecode dracut-network ignition gdisk rpm2cpio && \
    curl -L https://github.com/warewulf/warewulf/releases/download/v${WW_VERSION}/warewulf-dracut-${WW_VERSION}-1.el10.noarch.rpm | rpm2cpio | cpio -idmf && \
    echo 'add_dracutmodules+=" wwinit ignition "' >> /etc/dracut.conf.d/wwinit.conf

## Install firmware and kernel (ubuntu: linux-firmware-raspi) and kernel
RUN apt-get install --yes --no-install-recommends \
        raspi-firmware firmware-brcm80211 firmware-realtek wireless-regdb bluez-firmware && \
    apt-get install --yes --no-install-recommends linux-image-rpi-v8 && \
    chmod 644 /boot/firmware/initramfs8 && \
    rm -v /vmlinuz* /initrd.img*

## Configure system
LABEL firmware="efi"
RUN passwd -d root && \
    systemctl enable systemd-networkd.service && \
    cp /dev/null /etc/machine-id
