FROM registry.docker.com/library/debian:13

ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

# Update and setup Debian
RUN apt-get update && \
    apt-get install --yes apt-utils && \
    apt-get dist-upgrade --yes --purge

## Raspberry Pi OS Repository
RUN . /etc/os-release && \
    echo "deb http://archive.raspberrypi.org/debian/ ${VERSION_CODENAME} main" >> /etc/apt/sources.list.d/raspi.list && \
    apt-get update --allow-insecure-repositories && \
    apt-get install --yes --allow-unauthenticated raspberrypi-archive-keyring && \
    apt-get update && \
    apt-get dist-upgrade --yes

## Install kernel dependencies and configure Dracut
RUN apt-get install --yes dracut && \
    echo 'hostonly="no"' > /etc/dracut.conf.d/wwinit.conf

## Install firmware and kernel (ubuntu: linux-firmware-raspi) and kernel
RUN apt-get install --yes --no-install-recommends \
    raspi-firmware linux-image-rpi-v8 linux-image-rpi-2712 \
    firmware-brcm80211 firmware-realtek wireless-regdb bluez-firmware && \
    chmod 644 /boot/firmware/kernel8 /boot/firmware/initramfs8 && \
    rm -v /vmlinuz* /initrd.img*

## Install base packages
RUN apt-get install --yes --no-install-recommends curl jq zstd cpio pigz procps iproute2 && \
    apt-get install --yes --no-install-recommends init udev dbus polkitd && \
    apt-get install --yes --no-install-recommends systemd-timesyncd systemd-resolved ifupdown && \
    apt-get install --yes --no-install-recommends openssh-server python3 && \
    apt-get install --yes nano vim less bash-completion iputils-ping bind9-host

## Configure system
ENV OS_RELEASE='debian13'
RUN passwd -d root && \
    systemctl enable systemd-networkd.service && \
    cp /dev/null /etc/machine-id
